sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run build
before_install:
  - npm i -g npm@6.4.1
node_js:
  - "8"